### ISSUE TITLE
[BUG] Ped Glitch when cuffed in last stand

### ISSUE THREAD

**Issue by itsExpress** [i-kulgu/qb-policejob#10]
**Describe the bug**
When cuffing someone when they are in last stand state, they appear to visually glitch. The ped flickers etc

**To Reproduce**
1. Use handcuffs on a player in last stand state. 

**Expected behavior**
Remain stable in last stand

**Screenshots**
Will grab screenshots when I can next test this issue. 

**Questions (please complete the following information):**
 - When you last updated: Yesterday
 - Are you using custom resource? QBCore
 - Have you renamed `qb-` to something custom? no

**Comment by i-kulgu** [comment]
This is fixed in version 1.3.3
Please update your version.
