### ISSUE TITLE
[BUG] Can open armory with any jobs

### ISSUE THREAD

**Issue by Mat40** [i-kulgu/qb-policejob#21]
When you are police and then you change job to an other like realtor armory can be open

![image](https://github.com/i-kulgu/qb-policejob/assets/59476172/f540e829-6244-4211-8487-403df0fec284)

**Comment by Lorcasn9** [comment]
can you check that the target system checks jobType

**Comment by i-kulgu** [comment]
Update your target system (but i think you already did this and the problem is solved)
