### ISSUE TITLE
Make some kind of telling what you fixed/upgraded[SUGGESTION]

### ISSUE THREAD

**Issue by aleks247** [i-kulgu/qb-policejob#24]
**Is your feature request related to a problem? Please describe.**
This suggestion is not related to a problem, it's  just a facilitation for updating the resource

Make some kind of information what you exactly fixed/upgraded, like what file or what function, so it's more easy to update it without deleting the improvements you made for you server

**Comment by i-kulgu** [comment]
That is what github is already doing automatically.
If you go to the commits then you'll see a list where you can check every change on every commit : 

![image](https://github.com/i-kulgu/qb-policejob/assets/29943243/9a05513a-2a24-4a06-a845-71522a9415a7)

**Comment by aleks247** [comment]
Oh I forgot about that, sorry
