### ISSUE TITLE
[BUG] problem target interaction points

### ISSUE THREAD

**Issue by Brosky01** [i-kulgu/qb-policejob#28]
ok script is verry great thanks for sharing but there is some problems like with the target ! target start after the qb-policejob so there is always a deelay what make an error pop when a player loggin into the server it must be fixed bro ! 
and i tried like 3 target script it doesnt work for me tried to off on remove job and restart the target and policejob but the point trgets like duty garage.. never show
any solution ?

**Comment by ericb160** [comment]
have same problem here. also can't get labs to show.

**Comment by i-kulgu** [comment]
Start qb-target before the qb-policejob.
Just go to your server.cfg file and after ensuring qb-core add ensure qb-target.
