### ISSUE TITLE
[SUGGESTION] ox_inventory cuff player

### ISSUE THREAD

**Issue by xMeftu** [i-kulgu/qb-policejob#29]
Hey, its code to work cuff player with ox_inventory, just edit this for ur script 
`
RegisterNetEvent('police:client:CuffPlayer', function()

    if IsPedRagdoll(cache.ped) then return end
     local player, distance = GetClosestPlayer()
    if isTooFar(player, distance) then return end
    if exports.ox_inventory:Search('count', config.handcuffItems) == 0 then
        exports.qbx_core:Notify(Lang:t('error.no_cuff'), 'error')
        return
    end
    local playerId = GetPlayerServerId(player)
    if IsPedInAnyVehicle(GetPlayerPed(player), false) or cache.vehicle then
        exports.qbx_core:Notify(Lang:t('error.vehicle_cuff'), 'error')
        return
    end
    TriggerServerEvent('police:server:CuffPlayer', playerId, false)
    handCuffAnimation()
end)
`

**Comment by JulianClus** [comment]
Hello, it would be very useful for me to know how you installed it, I use ox_compat (replaces qb-menu and qb-imput), I use ox_target, and I use ox_inventory. I would really appreciate it.

**Comment by i-kulgu** [comment]
Latest version is already ox_inventory compatible.
