### ISSUE TITLE
[SUGGESTION] Add player movement when handcuffed

### ISSUE THREAD

**Issue by mwuhahaa** [i-kulgu/qb-policejob#30]
Can you add player movement when handcuffed or tell me how to do it? 

I tried everything and it does not work.

**Comment by Beasssss** [comment]
> Can you add player movement when handcuffed or tell me how to do it?
> 
> I tried everything and it does not work.

Look for Config.CuffItems and change the handcuffs to "cufftype = 49" at the end of the line beginning with 'handcuffs'

![image](https://github.com/i-kulgu/qb-policejob/assets/148637440/bda12703-ed5d-42d9-b95c-04502b23e828)

**Comment by mwuhahaa** [comment]
Omg, im so blind lol.
