### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by DispersiaRoleplay** [i-kulgu/qb-policejob#38]
when you take a car from the garage, it assigns the car as its own in the database. Even when the car is handed over, it remains in the database.

**Comment by i-kulgu** [comment]
> when you take a car from the garage, it assigns the car as its own in the database. Even when the car is handed over, it remains in the database.

You have enabled the option for owned cars, so even when you despawn your car, it is still yours because you own it.
If you don't want to use owned cars then change it in your config.
